// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ba7ZI1xiVsYDw89ov1VFZoz2OCF2xJ0',
    appId: '1:147842427178:web:4124f52ce08f50eae8d653',
    messagingSenderId: '147842427178',
    projectId: 'role-308e9',
    authDomain: 'role-308e9.firebaseapp.com',
    storageBucket: 'role-308e9.appspot.com',
    measurementId: 'G-R81T5YWT9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgcIgJWDKR_mAYAxIGLZzNDLhuGbxMY_0',
    appId: '1:147842427178:android:85c19d96055526c5e8d653',
    messagingSenderId: '147842427178',
    projectId: 'role-308e9',
    storageBucket: 'role-308e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3rzcC5BT-IJ6B8RYsqYKp_rcqVuoXK1Y',
    appId: '1:147842427178:ios:4fa622f11ac3cee0e8d653',
    messagingSenderId: '147842427178',
    projectId: 'role-308e9',
    storageBucket: 'role-308e9.appspot.com',
    iosClientId: '147842427178-64m3lmgqgtn4ccn6s9n2ug3ovrcqj202.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3rzcC5BT-IJ6B8RYsqYKp_rcqVuoXK1Y',
    appId: '1:147842427178:ios:412be8320350a751e8d653',
    messagingSenderId: '147842427178',
    projectId: 'role-308e9',
    storageBucket: 'role-308e9.appspot.com',
    iosClientId: '147842427178-v7ailpings3tqc6dupp9dnn300bmvem4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxi.RunnerTests',
  );
}
